# Generated by Django 2.2.5 on 2020-03-24 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enter', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='forms',
        ),
    ]
